pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"

    - name: git
      image: alpine/git
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
"""
    }
  }

  parameters {
    string(
      name: 'ECR_REPOSITORY_URL',
      defaultValue: '',
      description: 'ECR repository URL from Terraform output'
    )
  }

  environment {
    AWS_REGION = "eu-north-1"
    IMAGE_TAG  = "v1.0.${BUILD_NUMBER}"

    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context `pwd`/django-app \
              --dockerfile `pwd`/django-app/Dockerfile \
              --destination=$ECR_REPOSITORY_URL:$IMAGE_TAG \
              --cache=true
          '''
        }
      }
    }

    stage('Update Chart Image in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git clone https://$GIT_USERNAME:$GIT_PAT@github.com/WindyAlex/goit-devops-ci-cd.git repo
              cd repo
              git checkout lesson-8-9

              sed -i "s|repository: .*|repository: \\"$ECR_REPOSITORY_URL\\"|" lesson-7/charts/django-app/values.yaml
              sed -i "s|tag: .*|tag: \\"$IMAGE_TAG\\"|" lesson-7/charts/django-app/values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"

              git add lesson-7/charts/django-app/values.yaml
              git commit -m "[skip ci] Update image to $ECR_REPOSITORY_URL:$IMAGE_TAG" || echo "No changes"
              git push origin lesson-8-9
            '''
          }
        }
      }
    }
  }
}